### ISSUE TITLE
Duplicate list of names

### ISSUE THREAD

**Issue by sudeeprp** [Engin-Boot/no-oggy-in-cs-AleenaSaleem#1]
https://github.com/Engin-Boot/no-oggy-in-cs-AleenaSaleem/blob/11288ca6f16eeef785107f6ed040eac4945e7345/no_oggy.cs#L8

names2 will need to change every time there is a change in the input. How can we remove the duplication?

**Comment by AleenaSaleem** [comment]
Thank you so much for pointing out. Was just trying to figure out what the error was . I will handle the duplicates issue as well.
